version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5555:5555"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - mongo
    # environment:
    #   - MONGO_URI= mongodb://mongo:27017/MERNp1

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    # volumes:
    #   - ./frontend:/usr/src/app

  mongo:
    image: mongo:latest
    expose:
      - "27017"
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
